name = "cart"
type = "javascript"
account_id = "25fd4a605fa32029740e7374ebb26cab"
workers_dev = true

vars."www.reimajapan.com" = "reima-jp;e0370fdfeed9aeac00130441c6e2cf76;https://www-reimajapan-com.reima.workers.dev/cart"
vars."us.reima.com" = "reima-us;d2990d8e29e763239f8e8ff6cefc9ebe;https://reima-us.netlify.app/cart/"
vars."reima.finnishbabybox.com" = "reima-fbb;b924450022119a018c5612ab7dfc0864;https://reima-fbb.netlify.app/cart/"
vars."reima.finnishbabybox.com/jp/cart" = "finnish-baby-box-japan;9b3bd80e9adfd4edf699d6a8afa8635a;https://fbb-japan.netlify.app/jp/cart/"
vars."www.reima.ca" = "reima-canada;f116e71286381b2d0589b99a792d3ae7;https://www-reima-ca.reima.workers.dev/cart"
vars."demo.reima.ca" = "reima-jp;e0370fdfeed9aeac00130441c6e2cf76;https://reima-demo.netlify.app/cart"

[env.dev]
name = "cart-dev"
vars = { "cart-dev.reima.workers.dev" = "reima-se;499e5799ae1f44c3c7e4f8947e13aa18;https://reima-se.netlify.app/cart/" }
