name: Publish to Cloudflore

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
    - name: Bundle worker
      run: deno bundle sw.ts sw.js
    - name: Publish with wrangler
      uses: cloudflare/wrangler-action@1.2.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}